"""add fraud decisions

Revision ID: 0bed84b6e331
Revises: 51f90974f653
Create Date: 2026-10-08 12:09:34.223475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bed84b6e331'
down_revision: Union[str, Sequence[str], None] = '51f90974f653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('confirmed_fraud', 'false_positive', 'inconclusive')", name='ck_fraud_decisions_decision'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', name='uq_fraud_decisions_case_id')
    )
    op.create_index(op.f('ix_fraud_decisions_alert_id'), 'fraud_decisions', ['alert_id'], unique=False)
    op.create_index(op.f('ix_fraud_decisions_case_id'), 'fraud_decisions', ['case_id'], unique=False)
    op.create_index(op.f('ix_fraud_decisions_decision'), 'fraud_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_fraud_decisions_reviewed_by'), 'fraud_decisions', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_fraud_decisions_transaction_id'), 'fraud_decisions', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fraud_decisions_transaction_id'), table_name='fraud_decisions')
    op.drop_index(op.f('ix_fraud_decisions_reviewed_by'), table_name='fraud_decisions')
    op.drop_index(op.f('ix_fraud_decisions_decision'), table_name='fraud_decisions')
    op.drop_index(op.f('ix_fraud_decisions_case_id'), table_name='fraud_decisions')
    op.drop_index(op.f('ix_fraud_decisions_alert_id'), table_name='fraud_decisions')
    op.drop_table('fraud_decisions')
    # ### end Alembic commands ###
