"""add fraud rule explanations

Revision ID: 51f90974f653
Revises: 03f84ae784f8
Create Date: 2026-10-03 12:18:33.174234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51f90974f653'
down_revision: Union[str, Sequence[str], None] = '03f84ae784f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'fraud_scores',
        sa.Column(
            'rule_reasons',
            postgresql.JSONB(
                astext_type=sa.Text()
            ),
            server_default=sa.text(
                "'[]'::jsonb"
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fraud_scores', 'rule_reasons')
    # ### end Alembic commands ###
